_target_: models.CMCDSampler

defaults:
  - components@state_encoder: StateEncoding-PIS

  - components@time_encoder: TimeEncoding-PIS

  - components@control_model: JointPolicy-PIS

  - prior_energy: Gaussian

state_encoder: #Minkyu
  s_dim: ${energy.dim} #Minkyu
  s_emb_dim: 256 #Minkyu

time_encoder: #Minkyu
  t_emb_dim: 256 #Minkyu
  harmonics_dim: ${.t_emb_dim} #Minkyu

control_model:
  s_dim: ${energy.dim}
  s_emb_dim: ${model.state_encoder.s_emb_dim} #Minkyu
  t_dim: ${model.time_encoder.t_emb_dim} #Minkyu
  hidden_dim: 256 #Minkyu
  num_layers: 2 #Minkyu

neural_energy:  #Chaehyeon  
  input_dim: ${energy.dim}  #Chaehyeon

trajectory_length: 256

base_diffusion_rate: 1.0 #Minkyu

clipping: true
lgv_clip: 1e2
gfn_clip: 1e4

optimizer_cfg:
  lr_policy: 1e-3
  lr_flow: 1e-1
  weight_decay: 1e-7
  use_weight_decay: false

